# **PyTorch Fundementals**

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

Forum for questions: https://github.com/mrdbourke/pytorch-deep-learning/discussions*

Extra exercises and curriculum for section 00: https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.0+cu118


## **Introduction to Tensors**


### **Creating tensors**

PyTorch tensors are created using 'torch.Tensor()' = https://pytorch.org/docs/stable/tensors.html

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Get tensor back as Python int
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7, 8],[9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],[3, 6, 9],[2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### **Random Tensors**

Why random tensors? 

Random tensors are important because the way many neural networks learn is that they start with tensors full of a random numbers and adjust those random numbers to better represent the data. 

Start with random numbers -> look at data -> update random numbers -> look at data -> udate random numbers

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html


In [ ]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(1, 3, 4)
random_tensor

tensor([[[0.4058, 0.7902, 0.1374, 0.5764],
         [0.9913, 0.4002, 0.0213, 0.8762],
         [0.0300, 0.4699, 0.1480, 0.8039]]])

In [ ]:
random_tensor.ndim

3

In [ ]:
# Create a random tesnor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) # height, width, color channels (R,G,B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### **Zeros and Ones Tensors**

In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(size = (3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
random_tensor.dtype

torch.float32

### **Range of Tensors**

Torch arange - https://pytorch.org/docs/stable/generated/torch.arange.html

In [ ]:
# Use torch.range()
one_to_ten = torch.arange(start = 1, end = 11, step = 1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### **Tensor datatypes**

***Note*** datatype errors are one of the 3 most common errors in PyTorch and deep learning
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

Precision in Computing: https://en.wikipedia.org/wiki/Precision_(computer_science)

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype = None, # What datatype is the tensor?
                                                device = None, # What device is tensor on?
                                                requires_grad = False) # Track Gradient?
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3, 6, 9], dtype = torch.int64)
int_32_tensor

tensor([3, 6, 9])

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### **Getting Information from Tesnors** (tensor attributes)

1. Tensors not right datatype - to get datatype from a tensor, can use 'tensor.dtype'
2. Tensors not right shape - to get shape from tensor, can use 'tensor.shape'
3. Tensors not on the right device - to get device of tensor, can use 'tensor.device'

In [ ]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.1081, 0.8023, 0.2287, 0.3849],
        [0.2831, 0.4520, 0.7622, 0.4431],
        [0.3195, 0.7878, 0.5673, 0.5635]])

In [ ]:
# Find out details about tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.1081, 0.8023, 0.2287, 0.3849],
        [0.2831, 0.4520, 0.7622, 0.4431],
        [0.3195, 0.7878, 0.5673, 0.5635]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


### **Manipulating Tensors** (tensor operations)

Tensor operations include: 
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication


In [ ]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### **Matrix Multiplication**

Two main ways of performing multiplication

1. Elementwise
2. Matrix (dot product . )

In [ ]:
# Elementwise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 359 µs, sys: 917 µs, total: 1.28 ms
Wall time: 1.19 ms


In [ ]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 851 µs, sys: 0 ns, total: 851 µs
Wall time: 790 µs


tensor(14)

### **Shape Errors** 
* One of the most common errors in deep learning


In [ ]:
#   Shapes for Matrix Multiplication
# tensor_A = torch.tensor([[1, 2],[3, 4],[5, 6]])

# tensor_B = torch.tensor([[7, 8],[9, 10],[11, 12]])

# torch.mm(tensor_A, tensor_B) # torch.mm = torch.matmul
# Note: this line produces a shape error, commented out so as not to cause runtime issues

* To fix shape error, we will manipulate the shape of one tensor using **transpose**.
* A **transpose** switches the axes or dimensions of a given tensor 

See also, torch.transpose: https://pytorch.org/docs/stable/generated/torch.transpose.html

In [ ]:
tensor_B, tensor_B.shape

NameError: ignored

In [ ]:
tensor_B.T, tensor_B.T.shape

In [ ]:
# Matrix multiplication works when tensor_B is  (using .T)
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"\nNew shapes: tensor_A = {tensor_A.shape}, tensor_B.T = {tensor_B.T.shape}")
print(f"\nMultiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match ")
output = torch.mm(tensor_A, tensor_B.T) # transpose of B
print(f"\nOuput: {output}\n")
print(f"\nOutput Shape: {output.shape}\n")

### **Tensor Aggregation**

* Min, Max, Mean and Sum

**Documentation:** 

Max: https://pytorch.org/docs/stable/generated/torch.max.html <br>
Min: https://pytorch.org/docs/stable/generated/torch.min.html <br>
Mean: https://pytorch.org/docs/stable/generated/torch.mean.html <br>
Sum: https://pytorch.org/docs/stable/generated/torch.sum.html <br>

In [ ]:
# Create a tenso
x = torch.arange(0, 100, 10)
x

In [ ]:
# Find the min
torch.min(x), x.min()

In [ ]:
# Find the max
torch.max(x), x.max()

In [ ]:
# Find the mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean() # convert to float, otherwise dtype error 
# note: torch.mean() function requires a tensor of float32 dtype

In [ ]:
# Find the sum
torch.sum(x), x.sum()

### **Positional Min and Max**

In [ ]:
x

In [ ]:
# .argmin() returns the index position of the tensor's minimum value
x.argmin()

In [ ]:
x[0] # standard index for position 0

In [ ]:
# .argmax() returns index position of the tensor's maximum value
x.argmax()

In [ ]:
x[9] # standard index for position 9


### **Tensor Manipulation/Tensor Transformation**

**Definitions:**
* torch.reshape - Returns a tensor with the same data and number of elements as input, but with the specified shape.
* torch.Tensor.view - Return a view of an input tensor of certain shapes but keeps the same memory as the original tensor.
* torch.stack - Concatenates a sequence of tensors along a new dimension.
* torch.vstack - Concatenates a sequence of tensors along a new dimension.
* torch.hstack - Stack tensors in sequence horizontally (column wise).
* torch.squeeze - Returns a tensor with all specified dimensions of input of size 1 removed.
* torch.unsqueeze - Returns a new tensor with a dimension of size one inserted at the specified position.
* torch.permute - Returns a view of the original tensor input with its dimensions permuted.

**Documentation:** <br>
* torch.reshape - https://pytorch.org/docs/stable/generated/torch.reshape.html <br>
* torch.Tensor.view - https://pytorch.org/docs/stable/generated/torch.Tensor.view.html <br>
* torch.stack - https://pytorch.org/docs/stable/generated/torch.stack.html <br>
* torch.vstack - https://pytorch.org/docs/stable/generated/torch.vstack.html <br>
* torch.hstack - https://pytorch.org/docs/stable/generated/torch.hstack.html <br>
* torch.squeeze - https://pytorch.org/docs/stable/generated/torch.squeeze.html <br>
* torch.unsqueeze - https://pytorch.org/docs/stable/generated/torch.unsqueeze.html <br>
* torch.permute: https://pytorch.org/docs/stable/generated/torch.permute.html <br>


In [ ]:
# Create a tensor
import torch
x = torch.arange(1., 11.)
x, x.shape

In [ ]:
# Add extra dimension
x_reshaped = x.reshape(1, 10)
x_reshaped, x_reshaped.shape

In [ ]:
# Add extra dimension and make colmumn
x_reshaped = x.reshape(10, 1)
x_reshaped, x_reshaped.shape

In [ ]:
# reshape to 2 colums
x_reshaped = x.reshape(5, 2)
x_reshaped, x_reshaped.shape
# note: reshape must match the number of original dimensions

In [ ]:
# Change the view
z = x.view(1, 10)
z, z.shape

In [ ]:
# Changing z changes x (because a view of a tensor shares the same memory as the original)
z[:, 0] = 5
z, x

In [ ]:
# Stack tensors vertically
x_stacked = torch.stack([x, x, x, x], dim = 1)
x_stacked

In [ ]:
# Stack tensors vertically
x_stacked = torch.stack([x, x, x, x], dim = 0)
x_stacked

In [ ]:
# Using .vstack (same as dim = 0)
x_vstacked = torch.vstack([x, x, x, x])
x_vstacked

In [ ]:
# Using .hstack 
x_hstacked = torch.hstack([x, x, x, x])
x_hstacked

In [ ]:
# torch.squeeze() - removes all single dimensions from a target tensor
import torch
y = torch.arange(1., 10.)
y, y.shape

In [ ]:
# Add extra dimension
y_reshaped = y.reshape(1, 9)
y_reshaped, y_reshaped.shape

In [ ]:
# Remove the extra dimension (squeeze)
y_squeeze = y_reshaped.squeeze()
y_squeeze, y_squeeze.shape

In [ ]:
# torch.squeeze() print statements
print(f"Previous tensor: {y_reshaped}")
print(f"Previous shape: {y_reshaped.shape}")
print(f"\nNew tensor: {y_squeeze}")
print(f"New shape: {y_squeeze.shape}")

In [ ]:
# torch.unsqueeze() - Returns a new tensor with a dimension of size one inserted at the specified position.
print(f"Previous tensor: {y_squeeze} ")
print(f"Previous shape: {y_squeeze.shape}")

# add dimension with unsqueeze
y_unsqueezed = y_squeeze.unsqueeze(dim = 0)

print(f"\nNew tensor: {y_unsqueezed}")
print(f"New shape: {y_unsqueezed.shape}")

In [ ]:
# torch.permute - Returns a view of the original tensor input with its dimensions permuted.
a_original = torch.rand(size = (224, 224, 3)) #(height, width, color channels)

# permute the original to rearrange the axis (or dim) order
a_permuted = a_original.permute(2, 0, 1) # shifts axis 0 -> 1, 1 -> 2, 2 -> 0.

print(f"Previous shape: {a_original.shape}")
print(f"\nNew shape: {a_permuted.shape}") #(color channels, height, width)

### **Indexing and Slicing**

* In PyTorch, indexing works very similarly to how it does in NumPy. It allows you to select or modify portions of your tensor using the values of indices.
* Slicing: Similar to Python lists and numpy arrays, you can use slicing to get parts of the tensor.
* Integer array indexing: You can index with other tensors.
* Boolean mask indexing: You can index with boolean tensors.

**Documetation**

Indexing: https://pytorch.org/cppdocs/notes/tensor_indexing.html

In [ ]:
# create a tensor 3D tensor
import torch 
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

In [ ]:
# Index on tensor (x)
x[0]

In [ ]:
# Index on middle bracket (dim = 1)
x[0][0]

In [ ]:
# Index on innermost bracked (last dimension)
x[0][0][0]

In [ ]:
# x[1] is outside the defined tensor range, but how can we index to the 9? 
x[0][2][2]

In [ ]:
# Use ":" to select all of a target dimension
x[:,0], x[:,1], x[:,2]

In [ ]:
# Get all values of 0th and 1st dimensions, but only index 1 of 2nd dimensions
x[:, :, 0], x[:, :, 1], x[:, :, 2], x[:, 2, 2]
# Note: x[:, 2, 2] is the same as x[0][2][2] except the tensor is returned with brackets around the 9 which means? 

In [ ]:
# Basic Indexing
# Create a 2D tensor
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Index into the tensor
print(x[0, 1]) 

# In this example, x[0, 1] returns the element at the first row and the second column of the tensor

In addition to basic indexing, PyTorch supports other advanced indexing techniques:

In [ ]:
# Slicing: Similar to Python lists and numpy arrays, you can use slicing to get parts of the tensor.
print(x[:, 1]) 


# In this example, x[:, 1] returns all the elements in the second column.

In [ ]:
# Integer array indexing: You can index with other tensors.
print(x[[1, 2], [0, 2]])  

# In this example, x[[1, 2], [0, 2]] returns the elements at (1,0) and (2,2) as a vector.

In [ ]:
# Boolean mask indexing: You can index with boolean tensors.
mask = x > 5
print(x[mask])  

# In this example, x[mask] returns all elements in x that are greater than 5.

 Let's consider a 3D tensor for the following examples. We'll create a tensor with dimensions 3x3x3 for simplicity:

In [ ]:
# Create a 3D tensor
x = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                  [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
                  [[19, 20, 21], [22, 23, 24], [25, 26, 27]]])
x, x.shape

In [ ]:
# Select the second column from every matrix
print(x[:, :, 1])  

In [ ]:
# Select the second row from the every matrix
print(x[:, 1, :]) 

In [ ]:
# Select all rows and colums of the second matrix
print(x[1, :, :])

In [ ]:
# Select the second row of the second matrix
print(x[1, 1, :])

In [ ]:
# Select the second column of the second matrix
print(x[1, :, 1])

In [ ]:
# Select the first element in the second column of the second matrix
print(x[1, 0, 1])

In [ ]:
# Select the first element in the second row of the second matrix
print(x[1, 1, 0])

The three parts of the index for a 3D tensor x[i, j, k] represent:

i - Depth: This represents the index of the 2D matrix in the 3D tensor.

j - Row: This represents the row index within the selected 2D matrix.

k - Column: This represents the column index within the selected row of the 2D matrix.

Also, note that Python uses 0-based indexing, so the first element is at index 0.

### **More examples of slicing**

In [ ]:
import torch

# Create a 3D tensor
x = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                  [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
                  [[19, 20, 21], [22, 23, 24], [25, 26, 27]]])

x, x.shape

It is important to note the elements included when slicing before and after a given element:

In [ ]:
# Get the first 2 matrices, all rows, first 2 columns
print(x[:2, :, :2]) 

# Note: Slicing before an element such as ":2" returns all elements up to index 2, but does not include index 2 (or 3rd element)

In [ ]:
# From the second 2 matrices, all rows, first 2 columns
print(x[1:, :, :2]) 

# Note: Slicing after and element such as "1:" returns all elements after index 1 and includes index 1 (or 2nd element)

In [ ]:
# Print all rows and first two columns from the first and last matrix
result = x[[0, -1], :, :2]  # -1 is used to index the last element
print(result)

In [ ]:
# Print first and last rows and all columns from the 2nd 2 matrices
result = x[1:, [0, -1], :]  # -1 is used to index the last element
print(result)

In [ ]:
# Print first and last colums and all rows from the 1st 2 matrices
result = x[:2, :, [0, -1]]  # -1 is used to index the last element
print(result)

## **PyTorch and NumPy**

In PyTorch, NumPy is often used alongside as a complementary library. PyTorch provides a multi-dimensional array called a **Tensor** as its primary data structure for representing and manipulating data, similar to NumPy's **ndarray**. Both Tensors and ndarrays provide efficient storage and operations on multi-dimensional arrays of numerical data.

The PyTorch library is built to work seamlessly with NumPy arrays. You can convert a NumPy array to a PyTorch Tensor and vice versa. PyTorch provides a function called `torch.from_numpy(ndarray)` to convert a NumPy array to a PyTorch Tensor and `torch.Tensor.numpy()` to convert a PyTorch Tensor to a NumPy array.

***This integration allows you to take advantage of NumPy's extensive ecosystem of functions for numerical computation, data manipulation, and visualization alongside PyTorch's powerful deep learning capabilities.*** You can use NumPy operations on PyTorch Tensors and vice versa, making it convenient for data preprocessing, data loading, and post-processing tasks in machine learning pipelines.

Overall, NumPy in PyTorch acts as a bridge between the deep learning framework and the broader scientific computing ecosystem, enabling you to leverage the strengths of both libraries in your machine learning workflows.

**Documentation**

Pytorch and Numpy: https://pytorch.org/tutorials/beginner/examples_tensor/polynomial_numpy.html

In [ ]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) 
array, tensor

# note when converting from numpy -> pytorch, pytorch reflects numpy's default dtype (float64)

In [ ]:
array.dtype

In [ ]:
tensor.dtype

In [ ]:
# Defalut torch dtype
torch.arange(1.0, 8.0).dtype

In [ ]:
# Note: changing the value of original array does not effect the tensor once generated
array = array + 1
array, tensor

In [ ]:
# Tensor to Numpy array
tensor = torch.ones(7)
numpy_tensor  = tensor.numpy()
tensor, numpy_tensor

# note when converting from pytorch -> numpy, numpy reflects pytorch's default dtype (float32)

In [ ]:
# Note: changing the value of the original tensor does not effect the array once generated.
tensor = tensor + 1
tensor, numpy_tensor

In [ ]:
# Converting 3D NumPy array to PyTorch Tensor
numpy_array = np.array([[[1, 2, 3], [4, 5, 6]],
                       [[7, 8, 9], [10, 11, 12]],
                       [[13, 14, 15], [16, 17, 18]]])
torch_tensor = torch.from_numpy(numpy_array)
numpy_array, torch_tensor

In [ ]:
numpy_array.dtype, torch_tensor.dtype

In [ ]:
# Converting PyTorch Tensor to 3D NumPy array
torch_tensor2 = torch.tensor([[[19, 20, 21], [22, 23, 24]],
                             [[25, 26, 27], [28, 29, 30]],
                             [[31, 32, 33], [34, 35, 36]]])
numpy_array2 = torch_tensor2.numpy()
torch_tensor2, numpy_array2

In [ ]:
torch_tensor2.dtype, numpy_array2.dtype

## **Reproducibility and Random Seed**

Reproducibility is crucial in machine learning and deep learning because it allows researchers and practitioners to verify and compare results, debug code, and ensure that experiments are consistent and reliable.

However, achieving reproducibility in PyTorch can be challenging due to various factors, including parallel computations, GPU utilization, and random number generation. 

>**Definition**: Reproducibility refers to the ability to obtain consistent and deterministic results when running your code. It means that given the same input and random seed, your PyTorch code should produce identical results, including the same model weights, the same intermediate outputs, and the same random number sequences.

[Reproducibility Documentation:](https://pytorch.org/docs/stable/notes/randomness.html)<br>
[Random Seed Wiki:](https://en.wikipedia.org/wiki/Random_seed)

How neural networks learn: 
1. Start with random numbers
2. Tensor operations 
3. Update random numbers try to make them better representations of the data
4. Repeat again and again and again

In order to reduce randomness in neural networks and PyTorch comes the concept of **Random Seed**: 

>**Definition**: Set a random seed at the beginning of your code using `torch.manual_seed` to ensure that random number generation is consistent across different runs. Additionally, set seeds for other libraries or modules that involve randomness, such as numpy or CUDA.



In [ ]:
import torch

# Create 2 random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B) # checks if any elements are equal 

In [ ]:
# Create random, but reproducibple tensors

# Set the random seed
RANDOM_SEED = 42 # Because 42 is the answer to the universe! 
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

## **Accessing a GPU**


Accessing a GPU when using PyTorch can offer significant benefits, especially for deep learning tasks. Here are a few reasons why you would want to utilize a GPU with PyTorch:

1. Accelerated Computation
2. Model Training Efficiency
3. Larger Model Capacity
4. Real-time Inference
5. Libraries and Frameworks

To access a GPU with PyTorch, you need to ensure that you have the necessary hardware (an NVIDIA GPU) and compatible drivers installed. PyTorch provides CUDA support, allowing you to move tensors and models to the GPU and perform computations on it by using the .to() method or explicitly calling .cuda() or .cuda(device) on tensors and models.



### **GPU Options:** <br>
1. Easiest - Google Colab free, or Google Colab Pro ($10 a month)
2. Use your own - Need to find a good Nvidia card, or figure out options for my AMD card (a little trickier, still in beta) 
3. Cloud computing - GCP, AWS, Azure rent them. 

For 2 and 3 drivers (CUDA) need to be set up: https://pytorch.org/get-started/locally/i <br>
Additional resources for later: <br>
https://pytorch.org/docs/stable/notes/cuda.html <br>
https://pytorch.org/docs/stable/cuda.html <br>
https://github.com/IgorSusmelj/pytorch-styleguide

In [ ]:
# For Google Colab GPU, change runtime type, select GPU, save, and run this line to check
!nvidia-smi

### **Check for GPU access with PyTorch:** <br>


In [ ]:
# Once GPU is selected and checked from previous seciont run this
import torch
torch.cuda.is_available()

# returns True if functioning properly

Since PyTorch is capable of running compute on GPU and CPU, it's best practice to setup device agnostic code: <br>

E.g. rund on GPU if avialable, else defalt to CPU

In [ ]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

In [ ]:
# Count number of devices
torch.cuda.device_count()

# For way later if running on multiple GPU's 

### **Moving tensors (and models) between GPU and CPU**

By using these methods, you can easily move tensors between the CPU and GPU based on the availability of GPU resources and take advantage of GPU acceleration for computations.



In [ ]:
import torch

# Check if GPU is available
if torch.cuda.is_available():
    device = torch.device("cuda")  # Use GPU
else:
    device = torch.device("cpu")  # Use CPU

# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3], )

# Tensor not on GPU
print(tensor, tensor.device)


In [ ]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

In [ ]:
# If tensor is on GPU, can't transform it to Numpy
# tensor_on_gpu.numpy() returns following error
# TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
# To fix GPU tensor issue with NumPy, first set it back to the CPU
tensor_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_on_cpu

**End of Fundamentals.**